image: mono:latest

build:
  stage: build
  before_script: 
    - apt-get update && apt-get install libtool-bin autotools-dev automake intltool libcanberra-gtk3-0 libgtk3.0-cil-dev librsvg2-dev gnome-doc-utils yelp-tools make nunit nunit-console -y
  script: 
    - ./autogen.sh && ./configure --enable-tests
    - make
    - cd tests 
    - make run 
    - cd ..
    - make distcheck

