image: mono:latest

build:
  stage: build
  before_script: 
    - apt-get update && apt-get install meson intltool libcanberra-gtk3-0 libgtk3.0-cil-dev librsvg2-dev gnome-doc-utils yelp-tools nunit nunit-console -y
  script:
    - meson . _build -Dtests=true
    - ninja -C _build test install
